import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { StylesProvider } from '@/components/StylesContext'
// import Question from './page' NB here//////
import styles from '@/styles/QuestionOne.module.css'
// import Question from './page'
// import '@/styles/QuestionOne.module.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'COHK Question',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        // <html lang="en">
        <div className={inter.className}>
            <StylesProvider styles={styles}>
                {children}
                {/* Note here */}
                {/* <Question /> */}
            </StylesProvider>
        </div>
        // </html>
    )
}
