import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { StylesProvider } from '@/components/StylesContext'
import styles from '@/styles/Question.module.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'COHK Question',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className={inter.className}>
            <StylesProvider styles={styles}>
                {children}
            </StylesProvider>
        </div>
    )
}
